services:
  - type: web
    name: compassion-tracker
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: compassion-tracker-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

databases:
  - name: compassion-tracker-db
    databaseName: compassion_tracker
    user: compassion_tracker_user
    plan: free